DROP TABLE IF EXISTS graph;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_roles;

CREATE TABLE graph(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
	name VARCHAR(255),
	descriptor VARCHAR(255)
);

CREATE TABLE users(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(255) UNIQUE,
	enabled BIT(1),
	password VARCHAR(255)
);

CREATE TABLE user_roles(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(255) UNIQUE,
	user_role VARCHAR(255),
	user_ID INT,
	foreign key (user_ID) references users(ID)
);